// Frontend Development/handson_06/src/components/Header.jsx
import { Link } from "react-router-dom";

import { useSelector } from "react-redux";

function Header() {

  const enrolledCourses = useSelector(
    (state) => state.enrollment.enrolledCourses
  );

  return (

    <header className="header">

      <h1>Student Portal</h1>

      <nav>

        <Link to="/">Home</Link>

        <Link to="/courses">Courses</Link>

        <Link to="/profile">Profile</Link>

      </nav>

      <h3>Enrolled : {enrolledCourses.length}</h3>

    </header>

  );
}

export default Header;

// Frontend Development/handson_08/src/components/Header.vue
<template>

<header>

  <h1>Student Portal</h1>

  <nav>

    <RouterLink to="/">Home</RouterLink>

    <RouterLink to="/courses">Courses</RouterLink>

    <RouterLink to="/profile">
      Profile ({{ store.enrolledCourses.length }})
    </RouterLink>

  </nav>

</header>

</template>

<script setup>

import { RouterLink } from 'vue-router'
import { useEnrollmentStore } from '../stores/enrollment'

const store = useEnrollmentStore()

</script>

<style scoped>

header{

  background:#2c5aa0;
  color:white;

  padding:20px;

  display:flex;

  justify-content:space-between;

  align-items:center;

}

nav{

  display:flex;

  gap:20px;

}

a{

  color:white;

  text-decoration:none;

  font-weight:bold;

}

a:hover{

  text-decoration:underline;

}

</style>
